# tools/code_roast.py
import random

CODE_ROASTS = [
    "Clippy has fewer issues than your repo.",
    "Clippy would crash trying to interpret your syntax.",
    "Even Clippy ran away after seeing your script.",
    "Even GDB ran away after seeing your script.",
    "Even GitHub ran away after seeing your script.",
    "Even JavaScript callbacks ran away after seeing your script.",
    "Even Linus Torvalds ran away after seeing your script.",
    "Even MS Paint ran away after seeing your script.",
    "Even Meta ran away after seeing your script.",
    "Even Morse code ran away after seeing your script.",
    "Even Notepad ran away after seeing your script.",
    "Even Python 2.7 ran away after seeing your script.",
    "Even Stack Overflow ran away after seeing your script.",
    "Even TikTok trends ran away after seeing your script.",
    "Even VS Code ran away after seeing your script.",
    "Even a horror movie ran away after seeing your script.",
    "Even a toxic relationship ran away after seeing your script.",
    "Even an AI gone rogue ran away after seeing your script.",
    "Even black hole ran away after seeing your script.",
    "Even drama series ran away after seeing your script.",
    "Even memory leaks ran away after seeing your script.",
    "Even pigeons ran away after seeing your script.",
    "Even segmentation faults ran away after seeing your script.",
    "Even tarot cards ran away after seeing your script.",
    "GDB called—they want their bugs back.",
    "GitHub called—they want their bugs back.",
    "Guido van Rossum called—they want their bugs back.",
    "Guido van Rossum would crash trying to interpret your syntax.",
    "I've seen Clippy write cleaner logic with their tail.",
    "I've seen GDB handle errors better than your code.",
    "I've seen GitHub handle errors better than your code.",
    "I've seen GitHub write cleaner logic with their tail.",
    "I've seen Guido van Rossum handle errors better than your code.",
    "I've seen Guido van Rossum write cleaner logic with their tail.",
    "I've seen JavaScript callbacks handle errors better than your code.",
    "I've seen JavaScript callbacks write cleaner logic with their tail.",
    "I've seen Linus Torvalds handle errors better than your code.",
    "I've seen Linus Torvalds write cleaner logic with their tail.",
    "I've seen MS Paint handle errors better than your code.",
    "I've seen MS Paint write cleaner logic with their tail.",
    "I've seen Meta handle errors better than your code.",
    "I've seen Meta write cleaner logic with their tail.",
    "I've seen Morse code handle errors better than your code.",
    "I've seen Morse code write cleaner logic with their tail.",
    "I've seen Notepad write cleaner logic with their tail.",
    "I've seen Python 2.7 handle errors better than your code.",
    "I've seen Python 2.7 write cleaner logic with their tail.",
    "I've seen TikTok trends handle errors better than your code.",
    "I've seen TikTok trends write cleaner logic with their tail.",
    "I've seen VS Code handle errors better than your code.",
    "I've seen VS Code write cleaner logic with their tail.",
    "I've seen a horror movie write cleaner logic with their tail.",
    "I've seen a plate of spaghetti write cleaner logic with their tail.",
    "I've seen a toddler tantrum handle errors better than your code.",
    "I've seen a toxic relationship write cleaner logic with their tail.",
    "I've seen an AI gone rogue write cleaner logic with their tail.",
    "I've seen better structure in a bowl of GDB.",
    "I've seen better structure in a bowl of JavaScript callbacks.",
    "I've seen better structure in a bowl of MS Paint.",
    "I've seen better structure in a bowl of Meta.",
    "I've seen better structure in a bowl of Notepad.",
    "I've seen better structure in a bowl of Stack Overflow.",
    "I've seen better structure in a bowl of TikTok trends.",
    "I've seen better structure in a bowl of VS Code.",
    "I've seen better structure in a bowl of a plate of spaghetti.",
    "I've seen better structure in a bowl of a toddler tantrum.",
    "I've seen better structure in a bowl of a toxic relationship.",
    "I've seen better structure in a bowl of black hole.",
    "I've seen better structure in a bowl of memory leaks.",
    "I've seen better structure in a bowl of pigeons.",
    "I've seen better structure in a bowl of segmentation faults.",
    "I've seen better structure in a bowl of tarot cards.",
    "I've seen black hole handle errors better than your code.",
    "I've seen drama series handle errors better than your code.",
    "I've seen memory leaks handle errors better than your code.",
    "I've seen pigeons handle errors better than your code.",
    "I've seen pigeons write cleaner logic with their tail.",
    "I've seen segmentation faults handle errors better than your code.",
    "I've seen segmentation faults write cleaner logic with their tail.",
    "I've seen tarot cards handle errors better than your code.",
    "I've seen tarot cards write cleaner logic with their tail.",
    "If your code was a Clippy, even JavaScript callbacks wouldn't touch it.",
    "If your code was a Clippy, even an AI gone rogue wouldn't touch it.",
    "If your code was a GDB, even Guido van Rossum wouldn't touch it.",
    "If your code was a GitHub, even an AI gone rogue wouldn't touch it.",
    "If your code was a Guido van Rossum, even Meta wouldn't touch it.",
    "If your code was a Guido van Rossum, even drama series wouldn't touch it.",
    "If your code was a JavaScript callbacks, even drama series wouldn't touch it.",
    "If your code was a MS Paint, even a plate of spaghetti wouldn't touch it.",
    "If your code was a MS Paint, even a toddler tantrum wouldn't touch it.",
    "If your code was a Meta, even JavaScript callbacks wouldn't touch it.",
    "If your code was a Morse code, even VS Code wouldn't touch it.",
    "If your code was a Morse code, even tarot cards wouldn't touch it.",
    "If your code was a Python 2.7, even Linus Torvalds wouldn't touch it.",
    "If your code was a Python 2.7, even Morse code wouldn't touch it.",
    "If your code was a Python 2.7, even a toxic relationship wouldn't touch it.",
    "If your code was a Stack Overflow, even Python 2.7 wouldn't touch it.",
    "If your code was a Stack Overflow, even VS Code wouldn't touch it.",
    "If your code was a TikTok trends, even Guido van Rossum wouldn't touch it.",
    "If your code was a VS Code, even Clippy wouldn't touch it.",
    "If your code was a VS Code, even JavaScript callbacks wouldn't touch it.",
    "If your code was a VS Code, even pigeons wouldn't touch it.",
    "If your code was a a plate of spaghetti, even VS Code wouldn't touch it.",
    "If your code was a a plate of spaghetti, even a horror movie wouldn't touch it.",
    "If your code was a a toxic relationship, even drama series wouldn't touch it.",
    "If your code was a drama series, even Meta wouldn't touch it.",
    "If your code was a drama series, even Python 2.7 wouldn't touch it.",
    "If your code was a drama series, even memory leaks wouldn't touch it.",
    "If your code was a memory leaks, even Python 2.7 wouldn't touch it.",
    "If your code was a pigeons, even Notepad wouldn't touch it.",
    "If your code was a pigeons, even Python 2.7 wouldn't touch it.",
    "If your code was a pigeons, even memory leaks wouldn't touch it.",
    "If your code was a segmentation faults, even a toddler tantrum wouldn't touch it.",
    "If your code was a tarot cards, even black hole wouldn't touch it.",
    "JavaScript callbacks has fewer issues than your repo.",
    "JavaScript callbacks would crash trying to interpret your syntax.",
    "Linus Torvalds called—they want their bugs back.",
    "Linus Torvalds has fewer issues than your repo.",
    "Linus Torvalds would crash trying to interpret your syntax.",
    "MS Paint called—they want their bugs back.",
    "MS Paint has fewer issues than your repo.",
    "MS Paint would crash trying to interpret your syntax.",
    "Meta called—they want their bugs back.",
    "Meta has fewer issues than your repo.",
    "Meta would crash trying to interpret your syntax.",
    "Morse code called—they want their bugs back.",
    "Morse code has fewer issues than your repo.",
    "Morse code would crash trying to interpret your syntax.",
    "Notepad has fewer issues than your repo.",
    "Python 2.7 called—they want their bugs back.",
    "Python 2.7 would crash trying to interpret your syntax.",
    "Stack Overflow called—they want their bugs back.",
    "Stack Overflow has fewer issues than your repo.",
    "Stack Overflow would crash trying to interpret your syntax.",
    "The only pattern in your code is Clippy.",
    "The only pattern in your code is GDB.",
    "The only pattern in your code is GitHub.",
    "The only pattern in your code is Guido van Rossum.",
    "The only pattern in your code is JavaScript callbacks.",
    "The only pattern in your code is MS Paint.",
    "The only pattern in your code is Meta.",
    "The only pattern in your code is Notepad.",
    "The only pattern in your code is Python 2.7.",
    "The only pattern in your code is Stack Overflow.",
    "The only pattern in your code is a horror movie.",
    "The only pattern in your code is an AI gone rogue.",
    "The only pattern in your code is black hole.",
    "The only pattern in your code is drama series.",
    "The only pattern in your code is memory leaks.",
    "The only pattern in your code is pigeons.",
    "The only pattern in your code is segmentation faults.",
    "TikTok trends called—they want their bugs back.",
    "TikTok trends has fewer issues than your repo.",
    "TikTok trends would crash trying to interpret your syntax.",
    "You must be using Clippy as your debugger.",
    "You must be using GDB as your debugger.",
    "You must be using Guido van Rossum as your debugger.",
    "You must be using JavaScript callbacks as your debugger.",
    "You must be using Linus Torvalds as your debugger.",
    "You must be using Meta as your debugger.",
    "You must be using Morse code as your debugger.",
    "You must be using Notepad as your debugger.",
    "You must be using Python 2.7 as your debugger.",
    "You must be using TikTok trends as your debugger.",
    "You must be using a horror movie as your debugger.",
    "You must be using a plate of spaghetti as your debugger.",
    "You must be using a toxic relationship as your debugger.",
    "You must be using an AI gone rogue as your debugger.",
    "You must be using pigeons as your debugger.",
    "You must be using segmentation faults as your debugger.",
    "You must be using tarot cards as your debugger.",
    "Your GitHub skills make Guido van Rossum look like a rocket scientist.",
    "Your Guido van Rossum skills make GDB look like a rocket scientist.",
    "Your Guido van Rossum skills make memory leaks look like a rocket scientist.",
    "Your Linus Torvalds skills make GDB look like a rocket scientist.",
    "Your Linus Torvalds skills make memory leaks look like a rocket scientist.",
    "Your MS Paint skills make Stack Overflow look like a rocket scientist.",
    "Your Morse code skills make Meta look like a rocket scientist.",
    "Your Morse code skills make black hole look like a rocket scientist.",
    "Your Python 2.7 skills make a toxic relationship look like a rocket scientist.",
    "Your VS Code skills make GDB look like a rocket scientist.",
    "Your a toddler tantrum skills make MS Paint look like a rocket scientist.",
    "Your a toxic relationship skills make tarot cards look like a rocket scientist.",
    "Your an AI gone rogue skills make black hole look like a rocket scientist.",
    "Your an AI gone rogue skills make segmentation faults look like a rocket scientist.",
    "Your black hole skills make VS Code look like a rocket scientist.",
    "Your code is like a bad Clippy, everyone avoids it.",
    "Your code is like a bad JavaScript callbacks, everyone avoids it.",
    "Your code is like a bad Linus Torvalds, everyone avoids it.",
    "Your code is like a bad MS Paint, everyone avoids it.",
    "Your code is like a bad Meta, everyone avoids it.",
    "Your code is like a bad Python 2.7, everyone avoids it.",
    "Your code is like a bad Stack Overflow, everyone avoids it.",
    "Your code is like a bad VS Code, everyone avoids it.",
    "Your code is like a bad a horror movie, everyone avoids it.",
    "Your code is like a bad a toddler tantrum, everyone avoids it.",
    "Your code is like a bad a toxic relationship, everyone avoids it.",
    "Your code is like a bad an AI gone rogue, everyone avoids it.",
    "Your code is like a bad drama series, everyone avoids it.",
    "Your code is like a bad segmentation faults, everyone avoids it.",
    "Your code is so bad, GDB refused to run it.",
    "Your code is so bad, Guido van Rossum refused to run it.",
    "Your code is so bad, Linus Torvalds refused to run it.",
    "Your code is so bad, Morse code refused to run it.",
    "Your code is so bad, Notepad refused to run it.",
    "Your code is so bad, Stack Overflow refused to run it.",
    "Your code is so bad, TikTok trends refused to run it.",
    "Your code is so bad, a horror movie refused to run it.",
    "Your code is so bad, a toddler tantrum refused to run it.",
    "Your code is so bad, an AI gone rogue refused to run it.",
    "Your code is so bad, drama series refused to run it.",
    "Your code is so bad, memory leaks refused to run it.",
    "Your code is so bad, pigeons refused to run it.",
    "Your code is so bad, segmentation faults refused to run it.",
    "Your code is the reason Clippy has an outage every week.",
    "Your code is the reason GDB has an outage every week.",
    "Your code is the reason Guido van Rossum has an outage every week.",
    "Your code is the reason JavaScript callbacks has an outage every week.",
    "Your code is the reason Morse code has an outage every week.",
    "Your code is the reason Python 2.7 has an outage every week.",
    "Your code is the reason Stack Overflow has an outage every week.",
    "Your code is the reason TikTok trends has an outage every week.",
    "Your code is the reason VS Code has an outage every week.",
    "Your code is the reason a horror movie has an outage every week.",
    "Your code is the reason a toddler tantrum has an outage every week.",
    "Your code is the reason a toxic relationship has an outage every week.",
    "Your code is the reason an AI gone rogue has an outage every week.",
    "Your code is the reason black hole has an outage every week.",
    "Your code is the reason drama series has an outage every week.",
    "Your code is the reason memory leaks has an outage every week.",
    "Your code is the reason pigeons has an outage every week.",
    "Your code is the reason segmentation faults has an outage every week.",
    "Your code is what happens when a Clippy meets a keyboard.",
    "Your code is what happens when a GDB meets a keyboard.",
    "Your code is what happens when a JavaScript callbacks meets a keyboard.",
    "Your code is what happens when a MS Paint meets a keyboard.",
    "Your code is what happens when a Meta meets a keyboard.",
    "Your code is what happens when a Stack Overflow meets a keyboard.",
    "Your code is what happens when a TikTok trends meets a keyboard.",
    "Your code is what happens when a VS Code meets a keyboard.",
    "Your code is what happens when a a horror movie meets a keyboard.",
    "Your code is what happens when a a plate of spaghetti meets a keyboard.",
    "Your code is what happens when a a toddler tantrum meets a keyboard.",
    "Your code is what happens when a a toxic relationship meets a keyboard.",
    "Your code is what happens when a an AI gone rogue meets a keyboard.",
    "Your code is what happens when a black hole meets a keyboard.",
    "Your code is what happens when a tarot cards meets a keyboard.",
    "Your codebase is a shrine to Clippy.",
    "Your codebase is a shrine to GitHub.",
    "Your codebase is a shrine to Linus Torvalds.",
    "Your codebase is a shrine to MS Paint.",
    "Your codebase is a shrine to Meta.",
    "Your codebase is a shrine to Morse code.",
    "Your codebase is a shrine to VS Code.",
    "Your codebase is a shrine to a horror movie.",
    "Your codebase is a shrine to a toddler tantrum.",
    "Your codebase is a shrine to a toxic relationship.",
    "Your codebase is a shrine to drama series.",
    "Your codebase is a shrine to pigeons.",
    "Your codebase is a shrine to segmentation faults.",
    "Your codebase is a shrine to tarot cards.",
    "Your drama series skills make Clippy look like a rocket scientist.",
    "Your drama series skills make GitHub look like a rocket scientist.",
    "Your functions have more drama than Clippy.",
    "Your functions have more drama than GDB.",
    "Your functions have more drama than GitHub.",
    "Your functions have more drama than Guido van Rossum.",
    "Your functions have more drama than JavaScript callbacks.",
    "Your functions have more drama than Linus Torvalds.",
    "Your functions have more drama than MS Paint.",
    "Your functions have more drama than Meta.",
    "Your functions have more drama than Python 2.7.",
    "Your functions have more drama than VS Code.",
    "Your functions have more drama than a plate of spaghetti.",
    "Your functions have more drama than a toddler tantrum.",
    "Your functions have more drama than a toxic relationship.",
    "Your functions have more drama than an AI gone rogue.",
    "Your functions have more drama than black hole.",
    "Your functions have more drama than drama series.",
    "Your functions have more drama than memory leaks.",
    "Your functions have more drama than pigeons.",
    "Your functions have more drama than segmentation faults.",
    "Your functions have more drama than tarot cards.",
    "Your indentation caused a Linus Torvalds.",
    "Your indentation caused a Notepad.",
    "Your indentation caused a Python 2.7.",
    "Your indentation caused a Stack Overflow.",
    "Your indentation caused a VS Code.",
    "Your indentation caused a a plate of spaghetti.",
    "Your indentation caused a a toddler tantrum.",
    "Your indentation caused a a toxic relationship.",
    "Your indentation caused a drama series.",
    "Your indentation caused a tarot cards.",
    "Your logic is more twisted than a GDB.",
    "Your logic is more twisted than a GitHub.",
    "Your logic is more twisted than a MS Paint.",
    "Your logic is more twisted than a Meta.",
    "Your logic is more twisted than a Notepad.",
    "Your logic is more twisted than a Python 2.7.",
    "Your logic is more twisted than a Stack Overflow.",
    "Your logic is more twisted than a TikTok trends.",
    "Your logic is more twisted than a VS Code.",
    "Your logic is more twisted than a a horror movie.",
    "Your logic is more twisted than a a plate of spaghetti.",
    "Your logic is more twisted than a a toddler tantrum.",
    "Your logic is more twisted than a drama series.",
    "Your logic is more twisted than a pigeons.",
    "Your logic is more twisted than a segmentation faults.",
    "Your logic is more twisted than a tarot cards.",
    "Your tarot cards skills make GitHub look like a rocket scientist.",
    "Your tarot cards skills make Guido van Rossum look like a rocket scientist.",
    "Your variable names are inspired by Clippy.",
    "Your variable names are inspired by GDB.",
    "Your variable names are inspired by JavaScript callbacks.",
    "Your variable names are inspired by Linus Torvalds.",
    "Your variable names are inspired by MS Paint.",
    "Your variable names are inspired by Meta.",
    "Your variable names are inspired by Morse code.",
    "Your variable names are inspired by Python 2.7.",
    "Your variable names are inspired by Stack Overflow.",
    "Your variable names are inspired by a plate of spaghetti.",
    "Your variable names are inspired by a toddler tantrum.",
    "Your variable names are inspired by a toxic relationship.",
    "Your variable names are inspired by an AI gone rogue.",
    "Your variable names are inspired by segmentation faults.",
    "a horror movie called—they want their bugs back.",
    "a horror movie would crash trying to interpret your syntax.",
    "a plate of spaghetti has fewer issues than your repo.",
    "a plate of spaghetti would crash trying to interpret your syntax.",
    "a toddler tantrum called—they want their bugs back.",
    "a toddler tantrum has fewer issues than your repo.",
    "a toxic relationship called—they want their bugs back.",
    "a toxic relationship has fewer issues than your repo.",
    "an AI gone rogue called—they want their bugs back.",
    "an AI gone rogue has fewer issues than your repo.",
    "an AI gone rogue would crash trying to interpret your syntax.",
    "black hole called—they want their bugs back.",
    "black hole has fewer issues than your repo.",
    "drama series called—they want their bugs back.",
    "drama series has fewer issues than your repo.",
    "drama series would crash trying to interpret your syntax.",
    "memory leaks called—they want their bugs back.",
    "memory leaks would crash trying to interpret your syntax.",
    "pigeons called—they want their bugs back.",
    "segmentation faults called—they want their bugs back.",
    "segmentation faults has fewer issues than your repo.",
    "segmentation faults would crash trying to interpret your syntax.",
    "tarot cards called—they want their bugs back.",
    "tarot cards has fewer issues than your repo.",
    "tarot cards would crash trying to interpret your syntax."
]

def get_roast() -> str:
    """Returns a random code roast."""
    return random.choice(CODE_ROASTS)